import { Cdp } from './lib-cdp.mjs';
import { halamanZephyr } from './lib-zephyr-page.mjs';
import { writeFileSync } from 'node:fs';
const page = await halamanZephyr('9223');
const { cdp } = await Cdp.attach('9223', page.title);
const r = await cdp.runAsync(`
  const out = {};
  const ext = await import('/src/lib/extensionsStore19.ts');
  const stE = ext.useExt19.getState();
  out.tab = stE.tab;
  out.cari = stE.q;
  out.jumlahRegistry = (stE.registry || []).length;
  out.jumlahTerinstall = (stE.installed || []).length;
  out.jumlahRekomendasi = (stE.recommended || []).length;
  out.kunci = Object.keys(stE).join(",");
  out.error = stE.error || null;
  return out;
`, 90000);
console.log(JSON.stringify(r, null, 1));
const sh = await cdp.send('Page.captureScreenshot', { format: 'png' });
writeFileSync('D:/Zephyr/shot-ext.png', Buffer.from(sh.result.data, 'base64'));
cdp.close();
