import { Cdp } from './lib-cdp.mjs';
const list = await (await fetch('http://127.0.0.1:9223/json/list')).json();
console.log('TARGETS:', list.map(t => `${t.type}:${t.title}`).join(' | '));
const page = list.find((t) => t.type === 'page');
const { cdp } = await Cdp.attach('9223', page.title);
const r = await cdp.send('Runtime.evaluate', { expression: 'typeof window.__ZEPHYR__', returnByValue: true });
console.log('__ZEPHYR__:', JSON.stringify(r.result));
const r2 = await cdp.send('Runtime.evaluate', { expression: 'document.title + " | " + (document.querySelector("#root")||{}).childElementCount', returnByValue: true });
console.log('page:', JSON.stringify(r2.result));
cdp.close();
