import { Cdp } from './lib-cdp.mjs';
import { halamanZephyr } from './lib-zephyr-page.mjs';
const page = await halamanZephyr('9223');
const { cdp } = await Cdp.attach('9223', page.title);
const r = await cdp.runAsync(`
  const out = {};
  const host = q('[data-testid="ai-panel"]') || document.body;
  const w = document.createElement('div');
  w.style.cssText = 'position:fixed;left:20px;top:80px;z-index:99999;background:#111;padding:8px';
  const d = document.createElement('span');
  d.className = 'ai-dots';
  let h = '';
  for (let i = 0; i < 8; i++) h += '<span></span>';
  d.innerHTML = h;
  w.appendChild(d);
  document.body.appendChild(w);
  await wait(700);
  const sp = d.querySelectorAll('span');
  out.jumlah = sp.length;
  out.warna = [...sp].map(s => getComputedStyle(s).backgroundColor);
  out.warnaUnik = new Set(out.warna).size;
  out.bulat = getComputedStyle(sp[0]).borderRadius;
  out.animasi = getComputedStyle(sp[0]).animationName;
  out.animStrip = getComputedStyle(d).animationName;
  w.remove();
  return out;
`, 120000);
console.log(JSON.stringify(r, null, 1));
cdp.close();
