// terjemahan-panjang.mjs — kalimat panjang Settings (Security, MCP, Extensions).
//
// Dipakai scripts/suntik-panjang.mjs. Potongan-potongan ini adalah bagian
// kalimat yang dipecah oleh elemen <strong>/<code> di JSX, jadi kuncinya
// berupa penggalan, bukan kalimat utuh.

export const TERJEMAHAN_PANJANG = {
  'Folder yang belum dipercaya berjalan dalam': {
    en: 'Untrusted folders run in',
    ja: '信頼されていないフォルダは次で実行されます:',
    ko: '신뢰되지 않은 폴더는 다음에서 실행됩니다:',
    zh: '未受信任的文件夹以以下模式运行：',
    es: 'Las carpetas no confiables se ejecutan en',
    fr: 'Les dossiers non approuvés s’exécutent en',
    de: 'Nicht vertrauenswürdige Ordner laufen im',
    pt: 'Pastas não confiáveis são executadas em',
    ar: 'تُشغَّل المجلدات غير الموثوقة في',
  },
  ': file tetap bisa dibuka dan diedit, tapi tasks, debug, language server, dan ekstensi tidak dijalankan. Keputusan disimpan di': {
    en: ': files can still be opened and edited, but tasks, debug, language servers and extensions do not run. The decision is stored in',
    ja: '：ファイルは開いて編集できますが、タスク・デバッグ・言語サーバー・拡張機能は実行されません。判断は次に保存されます:',
    ko: ': 파일은 열고 편집할 수 있지만 작업, 디버그, 언어 서버, 확장은 실행되지 않습니다. 결정은 다음에 저장됩니다:',
    zh: '：文件仍可打开和编辑，但任务、调试、语言服务器和扩展不会运行。决定保存在',
    es: ': los archivos se pueden abrir y editar, pero las tareas, la depuración, los servidores de lenguaje y las extensiones no se ejecutan. La decisión se guarda en',
    fr: ' : les fichiers restent modifiables, mais tâches, débogage, serveurs de langage et extensions ne s’exécutent pas. La décision est enregistrée dans',
    de: ': Dateien lassen sich öffnen und bearbeiten, aber Tasks, Debug, Language Server und Erweiterungen laufen nicht. Die Entscheidung wird gespeichert in',
    pt: ': arquivos podem ser abertos e editados, mas tarefas, depuração, servidores de linguagem e extensões não são executados. A decisão fica em',
    ar: ': يمكن فتح الملفات وتحريرها، لكن المهام والتصحيح وخوادم اللغة والإضافات لا تعمل. يُحفظ القرار في',
  },
  'dan berlaku juga untuk subfolder.': {
    en: 'and also applies to subfolders.',
    ja: 'サブフォルダにも適用されます。',
    ko: '하위 폴더에도 적용됩니다.',
    zh: '并同样适用于子文件夹。',
    es: 'y también se aplica a las subcarpetas.',
    fr: 'et s’applique aussi aux sous-dossiers.',
    de: 'und gilt auch für Unterordner.',
    pt: 'e também vale para subpastas.',
    ar: 'وينطبق أيضاً على المجلدات الفرعية.',
  },
  'Saat switch ini hidup, Zephyr jadi server MCP di': {
    en: 'When this switch is on, Zephyr becomes an MCP server at',
    ja: 'このスイッチをオンにすると、Zephyr は次で MCP サーバーになります:',
    ko: '이 스위치를 켜면 Zephyr가 MCP 서버가 됩니다:',
    zh: '开启此开关后，Zephyr 将成为 MCP 服务器，地址：',
    es: 'Con este interruptor activado, Zephyr se convierte en servidor MCP en',
    fr: 'Quand ce commutateur est actif, Zephyr devient un serveur MCP sur',
    de: 'Ist dieser Schalter an, wird Zephyr zum MCP-Server auf',
    pt: 'Com este interruptor ligado, o Zephyr vira servidor MCP em',
    ar: 'عند تفعيل هذا المفتاح يصبح Zephyr خادم MCP على',
  },
  'AI CLI di luar (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) bisa membaca pane, tab editor, dan settings — juga mengemudikan jendela ini: mengetik di terminal, membuka file, menjalankan command. Hanya loopback: tidak pernah terbuka ke jaringan.': {
    en: 'External AI CLIs (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) can read panes, editor tabs and settings — and drive this window: type in the terminal, open files, run commands. Loopback only: never exposed to the network.',
    ja: '外部のAI CLI（Claude Code、Codex、Gemini CLI、opencode、Copilot CLI、Cursor）がペイン・エディタタブ・設定を読み、このウィンドウを操作できます。ループバックのみで、ネットワークには公開されません。',
    ko: '외부 AI CLI(Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor)가 페인, 에디터 탭, 설정을 읽고 이 창을 조작할 수 있습니다. 루프백 전용이며 네트워크에 노출되지 않습니다.',
    zh: '外部 AI CLI（Claude Code、Codex、Gemini CLI、opencode、Copilot CLI、Cursor）可读取窗格、编辑器标签和设置，并驱动此窗口。仅限回环，绝不暴露到网络。',
    es: 'Las CLI de IA externas (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) pueden leer paneles, pestañas del editor y ajustes — y manejar esta ventana. Solo loopback: nunca se expone a la red.',
    fr: 'Les CLI IA externes (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) peuvent lire les volets, onglets et réglages — et piloter cette fenêtre. Loopback uniquement : jamais exposé au réseau.',
    de: 'Externe KI-CLIs (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) können Panes, Editor-Tabs und Einstellungen lesen — und dieses Fenster steuern. Nur Loopback: nie im Netzwerk erreichbar.',
    pt: 'CLIs de IA externas (Claude Code, Codex, Gemini CLI, opencode, Copilot CLI, Cursor) podem ler painéis, abas do editor e configurações — e controlar esta janela. Somente loopback: nunca exposto à rede.',
    ar: 'يمكن لأدوات AI CLI الخارجية (Claude Code وCodex وGemini CLI وopencode وCopilot CLI وCursor) قراءة اللوحات وتبويبات المحرر والإعدادات — والتحكم في هذه النافذة. على loopback فقط: لا يُفتح على الشبكة أبداً.',
  },
  'Belum ada koneksi. Begitu sebuah AI CLI menyapa': {
    en: 'No connections yet. As soon as an AI CLI greets',
    ja: 'まだ接続はありません。AI CLI が次に挨拶すると:',
    ko: '아직 연결이 없습니다. AI CLI가 다음에 접속하면:',
    zh: '尚无连接。一旦有 AI CLI 访问',
    es: 'Aún no hay conexiones. En cuanto una CLI de IA salude a',
    fr: 'Aucune connexion. Dès qu’une CLI IA contacte',
    de: 'Noch keine Verbindungen. Sobald eine KI-CLI',
    pt: 'Nenhuma conexão ainda. Assim que uma CLI de IA acessar',
    ar: 'لا اتصالات بعد. بمجرد أن تنادي أداة AI CLI',
  },
  'atau memanggil tool, barisnya muncul di sini — bukti nyata, bukan klaim.': {
    en: 'or calls a tool, its line appears here — real evidence, not a claim.',
    ja: 'またはツールを呼び出すと、ここに行が表示されます — 主張ではなく実証です。',
    ko: '또는 도구를 호출하면 여기에 행이 나타납니다 — 주장이 아닌 실제 증거입니다.',
    zh: '或调用工具，其行会出现在这里 — 真实证据，而非声称。',
    es: 'o llame a una herramienta, su línea aparece aquí — evidencia real, no una afirmación.',
    fr: 'ou appelle un outil, sa ligne apparaît ici — preuve réelle, pas une affirmation.',
    de: 'oder ein Tool aufruft, erscheint hier die Zeile — echter Beleg, keine Behauptung.',
    pt: 'ou chamar uma ferramenta, a linha aparece aqui — evidência real, não promessa.',
    ar: 'أو استدعت أداة، يظهر سطرها هنا — دليل حقيقي لا مجرد ادعاء.',
  },
  'Terbuka di port': {
    en: 'Open on port',
    ja: 'ポートで公開:',
    ko: '포트에서 열림:',
    zh: '开放端口：',
    es: 'Abierto en el puerto',
    fr: 'Ouvert sur le port',
    de: 'Offen auf Port',
    pt: 'Aberto na porta',
    ar: 'مفتوح على المنفذ',
  },
  ': apa pun yang berjalan sebagai user-mu bisa mengemudikan jendela ini selama tahu tokennya.': {
    en: ': anything running as your user can drive this window as long as it knows the token.',
    ja: '：あなたのユーザーとして動くものは、トークンを知っていればこのウィンドウを操作できます。',
    ko: ': 사용자 권한으로 실행되는 모든 것이 토큰만 알면 이 창을 조작할 수 있습니다.',
    zh: '：任何以你的用户身份运行的进程，只要知道令牌就能驱动此窗口。',
    es: ': cualquier cosa que se ejecute como tu usuario puede manejar esta ventana si conoce el token.',
    fr: ' : tout ce qui tourne sous votre utilisateur peut piloter cette fenêtre s’il connaît le jeton.',
    de: ': Alles, was als dein Benutzer läuft, kann dieses Fenster steuern, wenn es das Token kennt.',
    pt: ': qualquer coisa rodando como seu usuário pode controlar esta janela se souber o token.',
    ar: ': أي شيء يعمل بحسابك يمكنه التحكم في هذه النافذة إن عرف الرمز.',
  },
  'hanya mengubah buffer tab, TIDAK menulis ke disk — penyimpanan tetap keputusanmu.': {
    en: 'only changes the tab buffer, does NOT write to disk — saving stays your decision.',
    ja: 'はタブのバッファを変えるだけで、ディスクには書き込みません — 保存はあなたの判断です。',
    ko: '는 탭 버퍼만 바꾸고 디스크에 쓰지 않습니다 — 저장은 당신의 결정입니다.',
    zh: '仅修改标签缓冲区，不写入磁盘 — 保存仍由你决定。',
    es: 'solo cambia el búfer de la pestaña, NO escribe en disco — guardar sigue siendo tu decisión.',
    fr: 'ne modifie que le tampon de l’onglet, n’écrit PAS sur le disque — l’enregistrement reste votre décision.',
    de: 'ändert nur den Tab-Puffer, schreibt NICHT auf die Platte — Speichern bleibt deine Entscheidung.',
    pt: 'apenas altera o buffer da aba, NÃO grava no disco — salvar continua sendo sua decisão.',
    ar: 'يغيّر مخزن التبويب فقط ولا يكتب على القرص — الحفظ يبقى قرارك.',
  },
  'dibatasi whitelist tampilan (tema, font, tab size); kredensial dan setting MCP sendiri tidak bisa diubah dari luar.': {
    en: 'is limited to a display whitelist (theme, font, tab size); credentials and MCP settings themselves cannot be changed from outside.',
    ja: 'は表示ホワイトリスト（テーマ、フォント、タブサイズ）に限定されています。資格情報とMCP設定自体は外部から変更できません。',
    ko: '는 표시 화이트리스트(테마, 글꼴, 탭 크기)로 제한됩니다. 자격 증명과 MCP 설정 자체는 외부에서 바꿀 수 없습니다.',
    zh: '仅限于显示白名单（主题、字体、制表符宽度）；凭据和 MCP 设置本身无法从外部更改。',
    es: 'se limita a una lista blanca de visualización (tema, fuente, tamaño de tabulación); las credenciales y los ajustes de MCP no se pueden cambiar desde fuera.',
    fr: 'est limité à une liste blanche d’affichage (thème, police, taille de tabulation) ; les identifiants et les réglages MCP ne sont pas modifiables de l’extérieur.',
    de: 'ist auf eine Anzeige-Whitelist beschränkt (Theme, Schrift, Tab-Größe); Zugangsdaten und MCP-Einstellungen selbst sind von außen nicht änderbar.',
    pt: 'é limitado a uma lista branca de exibição (tema, fonte, tamanho da tabulação); credenciais e configurações do MCP não podem ser alteradas de fora.',
    ar: 'محدود بقائمة عرض بيضاء (السمة، الخط، حجم الجدولة)؛ لا يمكن تغيير بيانات الاعتماد وإعدادات MCP من الخارج.',
  },
  'switch besar; port': {
    en: 'big switch; port',
    ja: '大きなスイッチ、ポート',
    ko: '큰 스위치, 포트',
    zh: '大开关；端口',
    es: 'interruptor grande; puerto',
    fr: 'grand commutateur ; port',
    de: 'großer Schalter; Port',
    pt: 'interruptor grande; porta',
    ar: 'مفتاح كبير؛ المنفذ',
  },
  'Belum ada. Ekstensi yang butuh runtime eksternal (Python, Java, Node, dll.) akan minta izin lewat dialog saat pertama kali memanggil': {
    en: 'None yet. Extensions that need an external runtime (Python, Java, Node, etc.) will ask for permission via a dialog the first time they call',
    ja: 'まだありません。外部ランタイム（Python、Java、Node など）が必要な拡張機能は、初回呼び出し時にダイアログで許可を求めます:',
    ko: '아직 없습니다. 외부 런타임(Python, Java, Node 등)이 필요한 확장은 처음 호출할 때 대화상자로 권한을 요청합니다:',
    zh: '暂无。需要外部运行时（Python、Java、Node 等）的扩展首次调用时会通过对话框请求授权：',
    es: 'Aún no hay ninguna. Las extensiones que necesiten un runtime externo (Python, Java, Node, etc.) pedirán permiso con un diálogo la primera vez que llamen a',
    fr: 'Aucune. Les extensions nécessitant un runtime externe (Python, Java, Node, etc.) demanderont l’autorisation via une boîte de dialogue au premier appel de',
    de: 'Noch keine. Erweiterungen mit externer Runtime (Python, Java, Node usw.) fragen beim ersten Aufruf von',
    pt: 'Nenhuma ainda. Extensões que precisam de runtime externo (Python, Java, Node etc.) pedirão permissão num diálogo na primeira chamada a',
    ar: 'لا شيء بعد. الإضافات التي تحتاج بيئة تشغيل خارجية (Python وJava وNode وغيرها) ستطلب الإذن عبر حوار عند أول استدعاء لـ',
  },
  '— eksekusi selalu di sisi Rust dari binary yang kamu setujui, dan bisa dicabut di sini.': {
    en: '— execution always happens on the Rust side, from a binary you approved, and can be revoked here.',
    ja: '— 実行は常に承認したバイナリを使いRust側で行われ、ここで取り消せます。',
    ko: '— 실행은 항상 승인한 바이너리로 Rust 쪽에서 이루어지며 여기서 취소할 수 있습니다.',
    zh: '— 执行始终在 Rust 侧、使用你批准的二进制文件进行，并可在此撤销。',
    es: '— la ejecución siempre ocurre en el lado Rust, desde un binario que aprobaste, y se puede revocar aquí.',
    fr: '— l’exécution se fait toujours côté Rust, depuis un binaire que vous avez approuvé, et peut être révoquée ici.',
    de: '— die Ausführung erfolgt immer auf der Rust-Seite, aus einer von dir bestätigten Binary, und kann hier widerrufen werden.',
    pt: '— a execução sempre acontece no lado Rust, a partir de um binário aprovado por você, e pode ser revogada aqui.',
    ar: '— يجري التنفيذ دائماً في جانب Rust من ملف ثنائي وافقت عليه، ويمكن إلغاؤه هنا.',
  },
};
