// terjemahan-hint.mjs — terjemahan untuk teks mentah (hint/label/title/placeholder)
// yang ditemukan scripts/scan-i18n-src.mjs.
//
// Struktur: { "<teks Indonesia>": { en, ja, ko, zh, es, fr, de, pt, ar } }
// Bahasa Indonesia memakai teks aslinya (kunci = nilainya).

export const TERJEMAHAN_HINT = {
  'dipakai editor & terminal': {
    en: 'used by the editor and terminal',
    ja: 'エディタとターミナルで使用',
    ko: '에디터와 터미널에서 사용',
    zh: '供编辑器和终端使用',
    es: 'usado por el editor y la terminal',
    fr: "utilisé par l'éditeur et le terminal",
    de: 'wird von Editor und Terminal verwendet',
    pt: 'usado pelo editor e terminal',
    ar: 'يُستخدم في المحرر والطرفية',
  },
  'label utama saja, bukan seluruh teks': {
    en: 'main labels only, not every string',
    ja: '主要なラベルのみ、全文ではありません',
    ko: '주요 라벨만, 전체 텍스트는 아님',
    zh: '仅主要标签，而非全部文本',
    es: 'solo las etiquetas principales, no todo el texto',
    fr: 'uniquement les libellés principaux, pas tout le texte',
    de: 'nur Hauptbeschriftungen, nicht jeder Text',
    pt: 'apenas os rótulos principais, não todo o texto',
    ar: 'التسميات الرئيسية فقط، وليس كل النصوص',
  },
  'tidak ada telemetri; hanya cek versi rilis': {
    en: 'no telemetry; only checks the release version',
    ja: 'テレメトリなし。リリース版の確認のみ',
    ko: '텔레메트리 없음, 릴리스 버전 확인만',
    zh: '无遥测；仅检查发布版本',
    es: 'sin telemetría; solo comprueba la versión de lanzamiento',
    fr: 'aucune télémétrie ; vérifie seulement la version publiée',
    de: 'keine Telemetrie; prüft nur die Release-Version',
    pt: 'sem telemetria; apenas verifica a versão de lançamento',
    ar: 'بلا قياسات؛ يتحقق فقط من إصدار الإصدار',
  },
  'Mode penghemat RAM': {
    en: 'RAM saver mode',
    ja: 'RAM節約モード',
    ko: 'RAM 절약 모드',
    zh: '内存节省模式',
    es: 'Modo de ahorro de RAM',
    fr: 'Mode économie de RAM',
    de: 'RAM-Sparmodus',
    pt: 'Modo de economia de RAM',
    ar: 'وضع توفير الذاكرة',
  },
  'smooth scroll off, minimap dipaksa off, batas tab termuat 4 (dari 12), scrollback terminal 2000 baris': {
    en: 'smooth scroll off, minimap forced off, loaded tab limit 4 (of 12), terminal scrollback 2000 lines',
    ja: 'スムーズスクロール無効、ミニマップ強制無効、読み込みタブ上限4（12中）、ターミナルスクロールバック2000行',
    ko: '부드러운 스크롤 끔, 미니맵 강제 끔, 로드 탭 한도 4(12 중), 터미널 스크롤백 2000줄',
    zh: '平滑滚动关闭，强制关闭小地图，加载标签页上限 4（共 12），终端回滚 2000 行',
    es: 'desplazamiento suave desactivado, minimapa forzado a off, límite de pestañas cargadas 4 (de 12), scrollback de terminal 2000 líneas',
    fr: "défilement fluide désactivé, minimap forcée désactivée, limite d'onglets chargés 4 (sur 12), scrollback du terminal 2000 lignes",
    de: 'Smooth Scrolling aus, Minimap zwangsweise aus, Limit geladener Tabs 4 (von 12), Terminal-Scrollback 2000 Zeilen',
    pt: 'rolagem suave desativada, minimapa forçado desativado, limite de abas carregadas 4 (de 12), scrollback do terminal 2000 linhas',
    ar: 'التمرير السلس معطّل، الخريطة المصغرة معطّلة قسراً، حد التبويبات المحمّلة 4 (من 12)، سجل الطرفية 2000 سطر',
  },
  'Tempat panel AI': {
    en: 'AI panel position',
    ja: 'AIパネルの位置',
    ko: 'AI 패널 위치',
    zh: 'AI 面板位置',
    es: 'Posición del panel de IA',
    fr: 'Position du panneau IA',
    de: 'Position des KI-Panels',
    pt: 'Posição do painel de IA',
    ar: 'موضع لوحة الذكاء الاصطناعي',
  },
  'bawah = sejajar terminal; kanan = kolom 340px ala VS Code': {
    en: 'bottom = aligned with terminal; right = 340px column, VS Code style',
    ja: '下＝ターミナルと並列、右＝VS Code風340pxカラム',
    ko: '아래 = 터미널과 나란히, 오른쪽 = VS Code 스타일 340px 열',
    zh: '下方 = 与终端对齐；右侧 = 仿 VS Code 的 340px 栏',
    es: 'abajo = alineado con la terminal; derecha = columna de 340px estilo VS Code',
    fr: 'bas = aligné sur le terminal ; droite = colonne de 340 px façon VS Code',
    de: 'unten = parallel zum Terminal; rechts = 340px-Spalte im VS-Code-Stil',
    pt: 'embaixo = alinhado ao terminal; direita = coluna de 340px estilo VS Code',
    ar: 'أسفل = بمحاذاة الطرفية؛ يمين = عمود 340 بكسل على طراز VS Code',
  },
  'Bawah (sejajar terminal)': {
    en: 'Bottom (aligned with terminal)',
    ja: '下（ターミナルと並列）',
    ko: '아래 (터미널과 나란히)',
    zh: '下方（与终端对齐）',
    es: 'Abajo (alineado con la terminal)',
    fr: 'Bas (aligné sur le terminal)',
    de: 'Unten (parallel zum Terminal)',
    pt: 'Embaixo (alinhado ao terminal)',
    ar: 'أسفل (بمحاذاة الطرفية)',
  },
  'Kanan (340px)': {
    en: 'Right (340px)',
    ja: '右（340px）',
    ko: '오른쪽 (340px)',
    zh: '右侧（340px）',
    es: 'Derecha (340px)',
    fr: 'Droite (340 px)',
    de: 'Rechts (340px)',
    pt: 'Direita (340px)',
    ar: 'يمين (340 بكسل)',
  },
  'editor = editor besar dengan terminal dock bawah; terminal = terminal jadi area utama, editor jadi pane samping': {
    en: 'editor = large editor with terminal docked below; terminal = terminal becomes the main area, editor becomes a side pane',
    ja: 'editor＝エディタを大きく、ターミナルを下部ドックに。terminal＝ターミナルがメイン、エディタはサイドペイン',
    ko: 'editor = 에디터 크게, 터미널 아래 도크; terminal = 터미널이 메인, 에디터는 사이드 페인',
    zh: 'editor = 大编辑器，终端停靠下方；terminal = 终端为主区域，编辑器变为侧边窗格',
    es: 'editor = editor grande con terminal acoplada abajo; terminal = la terminal pasa a ser el área principal y el editor un panel lateral',
    fr: "editor = grand éditeur avec terminal ancré en bas ; terminal = le terminal devient la zone principale, l'éditeur un panneau latéral",
    de: 'editor = großer Editor mit unten angedocktem Terminal; terminal = Terminal wird Hauptbereich, Editor wird Seitenleiste',
    pt: 'editor = editor grande com terminal acoplado abaixo; terminal = o terminal vira área principal e o editor vira painel lateral',
    ar: 'editor = محرر كبير مع طرفية مثبتة بالأسفل؛ terminal = تصبح الطرفية المنطقة الرئيسية والمحرر لوحة جانبية',
  },
  'mati secara default demi RAM': {
    en: 'off by default to save RAM',
    ja: 'RAM節約のため既定でオフ',
    ko: 'RAM 절약을 위해 기본 꺼짐',
    zh: '为节省内存默认关闭',
    es: 'desactivado por defecto para ahorrar RAM',
    fr: 'désactivé par défaut pour économiser la RAM',
    de: 'standardmäßig aus, um RAM zu sparen',
    pt: 'desativado por padrão para economizar RAM',
    ar: 'معطّل افتراضياً لتوفير الذاكرة',
  },
  'posisi saran snippet di daftar completion': {
    en: 'position of snippet suggestions in the completion list',
    ja: '補完リスト内でのスニペット候補の位置',
    ko: '완성 목록에서 스니펫 제안 위치',
    zh: '片段建议在补全列表中的位置',
    es: 'posición de las sugerencias de fragmentos en la lista de autocompletado',
    fr: 'position des suggestions de snippets dans la liste de complétion',
    de: 'Position der Snippet-Vorschläge in der Vervollständigungsliste',
    pt: 'posição das sugestões de snippets na lista de conclusão',
    ar: 'موضع اقتراحات المقاطع في قائمة الإكمال',
  },
  'lebih halus, sedikit lebih berat': {
    en: 'smoother, slightly heavier',
    ja: 'より滑らか、やや重い',
    ko: '더 부드럽지만 약간 무거움',
    zh: '更平滑，略重',
    es: 'más fluido, algo más pesado',
    fr: 'plus fluide, un peu plus lourd',
    de: 'flüssiger, etwas schwerer',
    pt: 'mais suave, um pouco mais pesado',
    ar: 'أكثر سلاسة، وأثقل قليلاً',
  },
  'titik untuk spasi, panah untuk tab': {
    en: 'dots for spaces, arrows for tabs',
    ja: 'スペースは点、タブは矢印',
    ko: '공백은 점, 탭은 화살표',
    zh: '空格显示为点，制表符显示为箭头',
    es: 'puntos para espacios, flechas para tabulaciones',
    fr: 'points pour les espaces, flèches pour les tabulations',
    de: 'Punkte für Leerzeichen, Pfeile für Tabs',
    pt: 'pontos para espaços, setas para tabulações',
    ar: 'نقاط للمسافات وأسهم للجدولة',
  },
  'jalur folder + simbol dari language server': {
    en: 'folder path + symbols from the language server',
    ja: 'フォルダパス＋言語サーバーのシンボル',
    ko: '폴더 경로 + 언어 서버 심볼',
    zh: '文件夹路径 + 来自语言服务器的符号',
    es: 'ruta de carpeta + símbolos del servidor de lenguaje',
    fr: 'chemin du dossier + symboles du serveur de langage',
    de: 'Ordnerpfad + Symbole vom Language Server',
    pt: 'caminho da pasta + símbolos do servidor de linguagem',
    ar: 'مسار المجلد + رموز من خادم اللغة',
  },
  'baris function/class menempel saat scroll': {
    en: 'function/class lines stick while scrolling',
    ja: 'スクロール時に関数/クラス行が固定される',
    ko: '스크롤 시 함수/클래스 줄 고정',
    zh: '滚动时函数/类行保持置顶',
    es: 'las líneas de función/clase se fijan al desplazar',
    fr: 'les lignes de fonction/classe restent collées au défilement',
    de: 'Funktions-/Klassenzeilen bleiben beim Scrollen haften',
    pt: 'linhas de função/classe ficam fixas ao rolar',
    ar: 'تثبيت أسطر الدوال/الأصناف أثناء التمرير',
  },
  'berapa baris header ditumpuk': {
    en: 'how many header lines are stacked',
    ja: 'ヘッダーを何行積み重ねるか',
    ko: '헤더 줄을 몇 개 쌓을지',
    zh: '堆叠的标题行数',
    es: 'cuántas líneas de encabezado se apilan',
    fr: "combien de lignes d'en-tête sont empilées",
    de: 'wie viele Kopfzeilen gestapelt werden',
    pt: 'quantas linhas de cabeçalho são empilhadas',
    ar: 'عدد أسطر الرأس المكدسة',
  },
  'gambar teks asli, bukan blok warna — jauh lebih berat': {
    en: 'renders real text, not color blocks — much heavier',
    ja: '色ブロックではなく実際の文字を描画 — はるかに重い',
    ko: '색 블록이 아닌 실제 텍스트 렌더링 — 훨씬 무거움',
    zh: '渲染真实文本而非色块 — 重得多',
    es: 'dibuja texto real, no bloques de color — mucho más pesado',
    fr: 'affiche le vrai texte, pas des blocs de couleur — bien plus lourd',
    de: 'zeichnet echten Text, keine Farbblöcke — deutlich schwerer',
    pt: 'desenha texto real, não blocos de cor — bem mais pesado',
    ar: 'يعرض نصاً حقيقياً لا كتل ألوان — أثقل بكثير',
  },
  'garis indentasi + indent aktif': {
    en: 'indent guides + active indent',
    ja: 'インデントガイド＋アクティブインデント',
    ko: '들여쓰기 가이드 + 활성 들여쓰기',
    zh: '缩进参考线 + 当前缩进',
    es: 'guías de sangría + sangría activa',
    fr: "guides d'indentation + indentation active",
    de: 'Einrückungslinien + aktive Einrückung',
    pt: 'guias de indentação + indentação ativa',
    ar: 'أدلة الإزاحة + الإزاحة النشطة',
  },
  'swatch #hex/rgb()/hsl(), klik untuk picker': {
    en: 'swatch for #hex/rgb()/hsl(), click for the picker',
    ja: '#hex/rgb()/hsl() のスウォッチ、クリックでピッカー',
    ko: '#hex/rgb()/hsl() 스와치, 클릭하면 피커',
    zh: '#hex/rgb()/hsl() 色板，点击打开取色器',
    es: 'muestra para #hex/rgb()/hsl(), clic para el selector',
    fr: 'nuancier pour #hex/rgb()/hsl(), cliquez pour le sélecteur',
    de: 'Farbfeld für #hex/rgb()/hsl(), klicken für den Picker',
    pt: 'amostra para #hex/rgb()/hsl(), clique para o seletor',
    ar: 'عيّنة للألوان #hex/rgb()/hsl()، انقر لفتح المنتقي',
  },
  'tandai karakter ambigu & tak terlihat': {
    en: 'flag ambiguous and invisible characters',
    ja: '曖昧な文字と不可視文字を強調',
    ko: '모호하고 보이지 않는 문자 표시',
    zh: '标记歧义和不可见字符',
    es: 'marca caracteres ambiguos e invisibles',
    fr: 'signale les caractères ambigus et invisibles',
    de: 'markiert mehrdeutige und unsichtbare Zeichen',
    pt: 'marca caracteres ambíguos e invisíveis',
    ar: 'تمييز الأحرف الملتبسة وغير المرئية',
  },
  'warna bracket per kedalaman': {
    en: 'bracket colors by depth',
    ja: '深さごとの括弧の色分け',
    ko: '깊이별 괄호 색상',
    zh: '按深度为括号着色',
    es: 'colores de paréntesis por profundidad',
    fr: 'couleurs des parenthèses par profondeur',
    de: 'Klammerfarben nach Tiefe',
    pt: 'cores de parênteses por profundidade',
    ar: 'ألوان الأقواس حسب العمق',
  },
  'Warna aksen': {
    en: 'Accent color',
    ja: 'アクセントカラー',
    ko: '강조 색상',
    zh: '强调色',
    es: 'Color de acento',
    fr: "Couleur d'accent",
    de: 'Akzentfarbe',
    pt: 'Cor de destaque',
    ar: 'لون التمييز',
  },
  'kosongkan untuk memakai warna tema': {
    en: 'leave empty to use the theme color',
    ja: '空欄にするとテーマの色を使用',
    ko: '비워 두면 테마 색상 사용',
    zh: '留空则使用主题颜色',
    es: 'déjalo vacío para usar el color del tema',
    fr: 'laisser vide pour utiliser la couleur du thème',
    de: 'leer lassen, um die Themenfarbe zu verwenden',
    pt: 'deixe vazio para usar a cor do tema',
    ar: 'اتركه فارغاً لاستخدام لون السمة',
  },
  'Latar belakang': {
    en: 'Background',
    ja: '背景',
    ko: '배경',
    zh: '背景',
    es: 'Fondo',
    fr: 'Arrière-plan',
    de: 'Hintergrund',
    pt: 'Plano de fundo',
    ar: 'الخلفية',
  },
  'pasang foto jadi background editor': {
    en: 'set a photo as the editor background',
    ja: '写真をエディタの背景に設定',
    ko: '사진을 에디터 배경으로 설정',
    zh: '将照片设为编辑器背景',
    es: 'pon una foto como fondo del editor',
    fr: "définir une photo comme arrière-plan de l'éditeur",
    de: 'ein Foto als Editor-Hintergrund festlegen',
    pt: 'definir uma foto como plano de fundo do editor',
    ar: 'تعيين صورة كخلفية للمحرر',
  },
  'Pilih gambar…': {
    en: 'Choose image…',
    ja: '画像を選択…',
    ko: '이미지 선택…',
    zh: '选择图片…',
    es: 'Elegir imagen…',
    fr: 'Choisir une image…',
    de: 'Bild wählen…',
    pt: 'Escolher imagem…',
    ar: 'اختيار صورة…',
  },
  Kekuatan: {
    en: 'Strength',
    ja: '強度',
    ko: '강도',
    zh: '强度',
    es: 'Intensidad',
    fr: 'Intensité',
    de: 'Stärke',
    pt: 'Intensidade',
    ar: 'الشدة',
  },
  'seberapa jelas gambar terlihat': {
    en: 'how visible the image is',
    ja: '画像の見え方の強さ',
    ko: '이미지가 얼마나 보이는지',
    zh: '图片的可见程度',
    es: 'cuán visible se ve la imagen',
    fr: "à quel point l'image est visible",
    de: 'wie deutlich das Bild sichtbar ist',
    pt: 'quão visível a imagem aparece',
    ar: 'مدى وضوح ظهور الصورة',
  },
  'Cara pasang': {
    en: 'Fit mode',
    ja: '配置方法',
    ko: '맞춤 방식',
    zh: '适配方式',
    es: 'Modo de ajuste',
    fr: "Mode d'ajustement",
    de: 'Anpassungsmodus',
    pt: 'Modo de ajuste',
    ar: 'طريقة الملاءمة',
  },
  'fill menutupi penuh, fit utuh, center asli': {
    en: 'fill covers fully, fit keeps it whole, center uses the original size',
    ja: 'fillは全体を覆い、fitは全体を収め、centerは原寸',
    ko: 'fill은 전체를 덮고, fit은 온전히 맞추고, center는 원본 크기',
    zh: 'fill 完全覆盖，fit 完整显示，center 原始大小',
    es: 'fill cubre todo, fit lo mantiene entero, center usa el tamaño original',
    fr: "fill couvre tout, fit garde l'ensemble, center taille d'origine",
    de: 'fill deckt vollständig ab, fit bleibt ganz, center Originalgröße',
    pt: 'fill cobre tudo, fit mantém inteiro, center usa o tamanho original',
    ar: 'fill يغطي بالكامل، fit يبقيها كاملة، center بالحجم الأصلي',
  },
  'Panel tembus pandang': {
    en: 'Transparent panel',
    ja: '透過パネル',
    ko: '투명 패널',
    zh: '透明面板',
    es: 'Panel transparente',
    fr: 'Panneau transparent',
    de: 'Transparentes Panel',
    pt: 'Painel transparente',
    ar: 'لوحة شفافة',
  },
  'matikan bila teks terasa kurang jelas': {
    en: 'turn off if the text looks unclear',
    ja: '文字が読みにくい場合はオフに',
    ko: '텍스트가 흐리면 끄세요',
    zh: '如果文字不清晰请关闭',
    es: 'desactívalo si el texto se ve poco claro',
    fr: 'désactivez si le texte paraît peu lisible',
    de: 'ausschalten, wenn der Text unklar wirkt',
    pt: 'desative se o texto parecer pouco claro',
    ar: 'أوقفه إذا بدا النص غير واضح',
  },
  'Kenyamanan editor di bawah ini bisa dimatikan satu per satu. Semuanya juga ada di menu View → Appearance.': {
    en: 'The editor comforts below can be turned off one by one. They are all also in the View → Appearance menu.',
    ja: '以下のエディタ快適機能は個別にオフにできます。すべて View → Appearance メニューにもあります。',
    ko: '아래 편의 기능은 하나씩 끌 수 있습니다. 모두 View → Appearance 메뉴에도 있습니다.',
    zh: '下方的编辑器辅助功能可逐项关闭。它们也都在 View → Appearance 菜单中。',
    es: 'Las comodidades del editor de abajo se pueden desactivar una por una. También están en el menú View → Appearance.',
    fr: "Les conforts d'éditeur ci-dessous peuvent être désactivés un par un. Ils sont aussi dans le menu View → Appearance.",
    de: 'Die Editor-Komfortfunktionen unten lassen sich einzeln abschalten. Sie sind auch im Menü View → Appearance.',
    pt: 'Os confortos do editor abaixo podem ser desativados um a um. Também estão no menu View → Appearance.',
    ar: 'يمكن إيقاف ميزات الراحة أدناه واحدة تلو الأخرى، وكلها موجودة أيضاً في قائمة View → Appearance.',
  },
  'Klik kolom shortcut lalu tekan kombinasi. Escape = batal. Kombinasi yang sudah dipakai action lain ditolak, jadi tidak mungkin ada dua action dengan shortcut sama.': {
    en: 'Click a shortcut cell then press the combination. Escape = cancel. Combinations already used by another action are rejected, so two actions can never share the same shortcut.',
    ja: 'ショートカット欄をクリックして組み合わせを押します。Escape＝キャンセル。他のアクションが使用中の組み合わせは拒否され、同じショートカットの重複は起こりません。',
    ko: '단축키 칸을 클릭한 뒤 조합을 누르세요. Escape = 취소. 다른 동작이 쓰는 조합은 거부되어 같은 단축키가 중복될 수 없습니다.',
    zh: '点击快捷键单元格后按下组合键。Escape = 取消。已被其他操作使用的组合会被拒绝，因此不会出现重复快捷键。',
    es: 'Haz clic en una celda de atajo y pulsa la combinación. Escape = cancelar. Las combinaciones ya usadas por otra acción se rechazan, así que nunca habrá dos acciones con el mismo atajo.',
    fr: 'Cliquez sur une cellule de raccourci puis appuyez sur la combinaison. Échap = annuler. Les combinaisons déjà utilisées sont refusées : deux actions ne peuvent jamais partager le même raccourci.',
    de: 'Klicke auf ein Tastenkürzel-Feld und drücke die Kombination. Escape = Abbrechen. Bereits belegte Kombinationen werden abgelehnt, doppelte Kürzel sind unmöglich.',
    pt: 'Clique numa célula de atalho e pressione a combinação. Escape = cancelar. Combinações já usadas por outra ação são rejeitadas, então nunca há dois atalhos iguais.',
    ar: 'انقر خلية الاختصار ثم اضغط المزيج. Escape = إلغاء. تُرفض المزائج المستخدمة من إجراء آخر، فلا يمكن تكرار الاختصار.',
  },
  'Perkiraan token (jumlah karakter ÷ 4)': {
    en: 'Estimated tokens (characters ÷ 4)',
    ja: '推定トークン数（文字数 ÷ 4）',
    ko: '예상 토큰 (문자 수 ÷ 4)',
    zh: '预计令牌数（字符数 ÷ 4）',
    es: 'Tokens estimados (caracteres ÷ 4)',
    fr: 'Jetons estimés (caractères ÷ 4)',
    de: 'Geschätzte Tokens (Zeichen ÷ 4)',
    pt: 'Tokens estimados (caracteres ÷ 4)',
    ar: 'الرموز المقدّرة (عدد الأحرف ÷ 4)',
  },
  'Salin isi jawaban': {
    en: 'Copy reply text',
    ja: '返答をコピー',
    ko: '답변 복사',
    zh: '复制回复内容',
    es: 'Copiar la respuesta',
    fr: 'Copier la réponse',
    de: 'Antwort kopieren',
    pt: 'Copiar a resposta',
    ar: 'نسخ نص الرد',
  },
  'Mode AI': {
    en: 'AI mode',
    ja: 'AIモード',
    ko: 'AI 모드',
    zh: 'AI 模式',
    es: 'Modo IA',
    fr: 'Mode IA',
    de: 'KI-Modus',
    pt: 'Modo IA',
    ar: 'وضع الذكاء الاصطناعي',
  },
  'API key tersimpan untuk provider ini': {
    en: 'API key saved for this provider',
    ja: 'このプロバイダーのAPIキーは保存済み',
    ko: '이 공급자의 API 키가 저장됨',
    zh: '此提供商已保存 API 密钥',
    es: 'Clave API guardada para este proveedor',
    fr: 'Clé API enregistrée pour ce fournisseur',
    de: 'API-Schlüssel für diesen Anbieter gespeichert',
    pt: 'Chave de API salva para este provedor',
    ar: 'مفتاح API محفوظ لهذا المزوّد',
  },
  'Posisi panel': {
    en: 'Panel position',
    ja: 'パネルの位置',
    ko: '패널 위치',
    zh: '面板位置',
    es: 'Posición del panel',
    fr: 'Position du panneau',
    de: 'Panel-Position',
    pt: 'Posição do painel',
    ar: 'موضع اللوحة',
  },
  'Panel Kiri — panel di samping kiri editor': {
    en: 'Left Panel — panel to the left of the editor',
    ja: '左パネル — エディタの左側のパネル',
    ko: '왼쪽 패널 — 에디터 왼쪽의 패널',
    zh: '左侧面板 — 编辑器左侧的面板',
    es: 'Panel izquierdo — panel a la izquierda del editor',
    fr: "Panneau gauche — panneau à gauche de l'éditeur",
    de: 'Linkes Panel — Panel links vom Editor',
    pt: 'Painel esquerdo — painel à esquerda do editor',
    ar: 'اللوحة اليسرى — لوحة على يسار المحرر',
  },
  'Panel Kiri': {
    en: 'Left Panel',
    ja: '左パネル',
    ko: '왼쪽 패널',
    zh: '左侧面板',
    es: 'Panel izquierdo',
    fr: 'Panneau gauche',
    de: 'Linkes Panel',
    pt: 'Painel esquerdo',
    ar: 'اللوحة اليسرى',
  },
  'Panel Kanan — panel di samping kanan editor': {
    en: 'Right Panel — panel to the right of the editor',
    ja: '右パネル — エディタの右側のパネル',
    ko: '오른쪽 패널 — 에디터 오른쪽의 패널',
    zh: '右侧面板 — 编辑器右侧的面板',
    es: 'Panel derecho — panel a la derecha del editor',
    fr: "Panneau droit — panneau à droite de l'éditeur",
    de: 'Rechtes Panel — Panel rechts vom Editor',
    pt: 'Painel direito — painel à direita do editor',
    ar: 'اللوحة اليمنى — لوحة على يمين المحرر',
  },
  'Panel Kanan': {
    en: 'Right Panel',
    ja: '右パネル',
    ko: '오른쪽 패널',
    zh: '右侧面板',
    es: 'Panel derecho',
    fr: 'Panneau droit',
    de: 'Rechtes Panel',
    pt: 'Painel direito',
    ar: 'اللوحة اليمنى',
  },
  'Panel Bawah — panel di bawah editor': {
    en: 'Bottom Panel — panel below the editor',
    ja: '下パネル — エディタ下部のパネル',
    ko: '아래 패널 — 에디터 아래의 패널',
    zh: '底部面板 — 编辑器下方的面板',
    es: 'Panel inferior — panel debajo del editor',
    fr: "Panneau inférieur — panneau sous l'éditeur",
    de: 'Unteres Panel — Panel unter dem Editor',
    pt: 'Painel inferior — painel abaixo do editor',
    ar: 'اللوحة السفلية — لوحة أسفل المحرر',
  },
  'Panel Bawah': {
    en: 'Bottom Panel',
    ja: '下パネル',
    ko: '아래 패널',
    zh: '底部面板',
    es: 'Panel inferior',
    fr: 'Panneau inférieur',
    de: 'Unteres Panel',
    pt: 'Painel inferior',
    ar: 'اللوحة السفلية',
  },
  'Panel bawah': {
    en: 'Bottom panel',
    ja: '下パネル',
    ko: '아래 패널',
    zh: '底部面板',
    es: 'Panel inferior',
    fr: 'Panneau inférieur',
    de: 'Unteres Panel',
    pt: 'Painel inferior',
    ar: 'اللوحة السفلية',
  },
  'Tab panel bawah': {
    en: 'Bottom panel tabs',
    ja: '下パネルのタブ',
    ko: '아래 패널 탭',
    zh: '底部面板标签',
    es: 'Pestañas del panel inferior',
    fr: 'Onglets du panneau inférieur',
    de: 'Tabs des unteren Panels',
    pt: 'Abas do painel inferior',
    ar: 'تبويبات اللوحة السفلية',
  },
  'Login GitHub (buka browser)': {
    en: 'GitHub login (opens browser)',
    ja: 'GitHubログイン（ブラウザを開く）',
    ko: 'GitHub 로그인 (브라우저 열기)',
    zh: 'GitHub 登录（打开浏览器）',
    es: 'Iniciar sesión en GitHub (abre el navegador)',
    fr: 'Connexion GitHub (ouvre le navigateur)',
    de: 'GitHub-Anmeldung (öffnet den Browser)',
    pt: 'Login no GitHub (abre o navegador)',
    ar: 'تسجيل الدخول إلى GitHub (يفتح المتصفح)',
  },
  'Font size (angka)': {
    en: 'Font size (number)',
    ja: 'フォントサイズ（数値）',
    ko: '글꼴 크기 (숫자)',
    zh: '字体大小（数字）',
    es: 'Tamaño de fuente (número)',
    fr: 'Taille de police (nombre)',
    de: 'Schriftgröße (Zahl)',
    pt: 'Tamanho da fonte (número)',
    ar: 'حجم الخط (رقم)',
  },
  'Line height (angka)': {
    en: 'Line height (number)',
    ja: '行の高さ（数値）',
    ko: '줄 높이 (숫자)',
    zh: '行高（数字）',
    es: 'Altura de línea (número)',
    fr: 'Hauteur de ligne (nombre)',
    de: 'Zeilenhöhe (Zahl)',
    pt: 'Altura da linha (número)',
    ar: 'ارتفاع السطر (رقم)',
  },
  'Zoom (angka)': {
    en: 'Zoom (number)',
    ja: 'ズーム（数値）',
    ko: '확대/축소 (숫자)',
    zh: '缩放（数字）',
    es: 'Zoom (número)',
    fr: 'Zoom (nombre)',
    de: 'Zoom (Zahl)',
    pt: 'Zoom (número)',
    ar: 'التكبير (رقم)',
  },
  'Tab size (angka)': {
    en: 'Tab size (number)',
    ja: 'タブサイズ（数値）',
    ko: '탭 크기 (숫자)',
    zh: '制表符宽度（数字）',
    es: 'Tamaño de tabulación (número)',
    fr: 'Taille de tabulation (nombre)',
    de: 'Tab-Größe (Zahl)',
    pt: 'Tamanho da tabulação (número)',
    ar: 'حجم الجدولة (رقم)',
  },
  'Sticky scroll max lines (angka)': {
    en: 'Sticky scroll max lines (number)',
    ja: 'スティッキースクロール最大行数（数値）',
    ko: '고정 스크롤 최대 줄 (숫자)',
    zh: '粘性滚动最大行数（数字）',
    es: 'Líneas máx. de scroll fijo (número)',
    fr: 'Lignes max. de défilement collé (nombre)',
    de: 'Max. Zeilen für Sticky Scroll (Zahl)',
    pt: 'Máx. de linhas do scroll fixo (número)',
    ar: 'الحد الأقصى لأسطر التمرير الثابت (رقم)',
  },
  'Durasi minimum notifikasi (angka)': {
    en: 'Minimum notification duration (number)',
    ja: '通知の最小表示時間（数値）',
    ko: '최소 알림 시간 (숫자)',
    zh: '最短通知时长（数字）',
    es: 'Duración mínima de notificación (número)',
    fr: 'Durée minimale de notification (nombre)',
    de: 'Minimale Benachrichtigungsdauer (Zahl)',
    pt: 'Duração mínima da notificação (número)',
    ar: 'الحد الأدنى لمدة الإشعار (رقم)',
  },
  'Max panes per tab (angka)': {
    en: 'Max panes per tab (number)',
    ja: 'タブあたりの最大ペイン数（数値）',
    ko: '탭당 최대 페인 (숫자)',
    zh: '每标签页最大窗格数（数字）',
    es: 'Máx. paneles por pestaña (número)',
    fr: 'Panneaux max. par onglet (nombre)',
    de: 'Max. Panes pro Tab (Zahl)',
    pt: 'Máx. painéis por aba (número)',
    ar: 'الحد الأقصى للوحات لكل تبويب (رقم)',
  },
  'Maximum parallel subagents (angka)': {
    en: 'Maximum parallel subagents (number)',
    ja: '並列サブエージェント最大数（数値）',
    ko: '최대 병렬 서브에이전트 (숫자)',
    zh: '最大并行子代理数（数字）',
    es: 'Subagentes paralelos máximos (número)',
    fr: 'Sous-agents parallèles max. (nombre)',
    de: 'Max. parallele Subagenten (Zahl)',
    pt: 'Máx. de subagentes paralelos (número)',
    ar: 'الحد الأقصى للوكلاء الفرعيين المتوازيين (رقم)',
  },
  'Step limit per subagent (angka)': {
    en: 'Step limit per subagent (number)',
    ja: 'サブエージェントごとのステップ上限（数値）',
    ko: '서브에이전트당 단계 한도 (숫자)',
    zh: '每个子代理的步骤上限（数字）',
    es: 'Límite de pasos por subagente (número)',
    fr: "Limite d'étapes par sous-agent (nombre)",
    de: 'Schrittlimit pro Subagent (Zahl)',
    pt: 'Limite de passos por subagente (número)',
    ar: 'حد الخطوات لكل وكيل فرعي (رقم)',
  },
  'Mode screen reader': {
    en: 'Screen reader mode',
    ja: 'スクリーンリーダーモード',
    ko: '스크린 리더 모드',
    zh: '屏幕阅读器模式',
    es: 'Modo lector de pantalla',
    fr: "Mode lecteur d'écran",
    de: 'Screenreader-Modus',
    pt: 'Modo leitor de tela',
    ar: 'وضع قارئ الشاشة',
  },
  'terminal & editor dioptimalkan untuk Narrator/NVDA (lebih berat)': {
    en: 'terminal & editor optimised for Narrator/NVDA (heavier)',
    ja: 'ターミナルとエディタをNarrator/NVDA向けに最適化（より重い）',
    ko: '터미널과 에디터를 Narrator/NVDA에 최적화 (더 무거움)',
    zh: '终端与编辑器针对 Narrator/NVDA 优化（更重）',
    es: 'terminal y editor optimizados para Narrator/NVDA (más pesado)',
    fr: 'terminal et éditeur optimisés pour Narrator/NVDA (plus lourd)',
    de: 'Terminal & Editor für Narrator/NVDA optimiert (schwerer)',
    pt: 'terminal e editor otimizados para Narrator/NVDA (mais pesado)',
    ar: 'الطرفية والمحرر مهيآن لـ Narrator/NVDA (أثقل)',
  },
  'pindahkan fokus ke dialog saat dibuka (matikan bila mengganggu)': {
    en: 'move focus to the dialog when it opens (turn off if disruptive)',
    ja: 'ダイアログを開いたときフォーカスを移す（邪魔ならオフ）',
    ko: '대화상자가 열리면 포커스 이동 (방해되면 끄세요)',
    zh: '打开对话框时移动焦点（若造成干扰请关闭）',
    es: 'mover el foco al diálogo al abrirse (desactiva si molesta)',
    fr: "déplacer le focus vers la boîte de dialogue à l'ouverture (désactiver si gênant)",
    de: 'Fokus beim Öffnen auf den Dialog setzen (aus, wenn störend)',
    pt: 'mover o foco para o diálogo ao abrir (desative se atrapalhar)',
    ar: 'نقل التركيز إلى الحوار عند فتحه (أوقفه إذا أزعجك)',
  },
  'screen reader butuh waktu membacakan; naikkan bila toast terlalu cepat hilang': {
    en: 'screen readers need time to read; raise it if toasts vanish too fast',
    ja: 'スクリーンリーダーは読み上げに時間がかかります。トーストが早すぎる場合は上げてください',
    ko: '스크린 리더는 읽을 시간이 필요합니다. 토스트가 너무 빨리 사라지면 늘리세요',
    zh: '屏幕阅读器需要时间朗读；若提示消失太快请调高',
    es: 'los lectores de pantalla necesitan tiempo; súbelo si los avisos desaparecen muy rápido',
    fr: "les lecteurs d'écran ont besoin de temps ; augmentez si les toasts disparaissent trop vite",
    de: 'Screenreader brauchen Zeit; erhöhen, wenn Toasts zu schnell verschwinden',
    pt: 'leitores de tela precisam de tempo; aumente se os toasts somem rápido demais',
    ar: 'يحتاج قارئ الشاشة وقتاً للقراءة؛ ارفعه إذا اختفت التنبيهات بسرعة',
  },
  'Hanya build debug: memicu panic di Rust untuk menguji panic hook + dialog crash': {
    en: 'Debug builds only: triggers a Rust panic to test the panic hook + crash dialog',
    ja: 'デバッグビルド限定：panic hook とクラッシュダイアログを試すためRustでpanicを起こします',
    ko: '디버그 빌드 전용: panic 훅과 크래시 대화상자를 시험하려 Rust panic을 발생시킵니다',
    zh: '仅调试构建：触发 Rust panic 以测试 panic 钩子和崩溃对话框',
    es: 'Solo en compilaciones debug: provoca un panic de Rust para probar el panic hook y el diálogo de fallo',
    fr: 'Builds debug uniquement : déclenche un panic Rust pour tester le panic hook et la boîte de crash',
    de: 'Nur Debug-Builds: löst einen Rust-Panic aus, um Panic-Hook und Absturzdialog zu testen',
    pt: 'Apenas builds debug: dispara um panic de Rust para testar o panic hook e o diálogo de falha',
    ar: 'لبنيات التصحيح فقط: يطلق panic في Rust لاختبار خطّاف panic وحوار الانهيار',
  },
  'Menulis stack ke log lalu memunculkan dialog crash. Tombol ini tidak ada di build release.': {
    en: 'Writes the stack to the log then shows the crash dialog. This button does not exist in release builds.',
    ja: 'スタックをログに書き、クラッシュダイアログを表示します。このボタンはリリースビルドにはありません。',
    ko: '스택을 로그에 쓰고 크래시 대화상자를 띄웁니다. 이 버튼은 릴리스 빌드에 없습니다.',
    zh: '将堆栈写入日志后弹出崩溃对话框。此按钮在发布构建中不存在。',
    es: 'Escribe el stack en el log y muestra el diálogo de fallo. Este botón no existe en las compilaciones release.',
    fr: "Écrit la pile dans le journal puis affiche la boîte de crash. Ce bouton n'existe pas en build release.",
    de: 'Schreibt den Stack ins Log und zeigt den Absturzdialog. Diesen Button gibt es nur in Debug-Builds.',
    pt: 'Grava o stack no log e mostra o diálogo de falha. Este botão não existe em builds release.',
    ar: 'يكتب المكدس في السجل ثم يعرض حوار الانهيار. هذا الزر غير موجود في بنيات الإصدار.',
  },
  'Pakai server RAG (mis. enowx-rag di localhost:7777) untuk mencari konteks project sebelum menjawab. Mati = chat biasa.': {
    en: 'Use a RAG server (e.g. enowx-rag on localhost:7777) to search project context before answering. Off = plain chat.',
    ja: '回答前にRAGサーバー（例：localhost:7777 の enowx-rag）でプロジェクト文脈を検索します。オフ＝通常チャット。',
    ko: '답변 전에 RAG 서버(예: localhost:7777의 enowx-rag)로 프로젝트 맥락을 검색합니다. 끔 = 일반 채팅.',
    zh: '回答前用 RAG 服务器（如 localhost:7777 的 enowx-rag）检索项目上下文。关闭 = 普通聊天。',
    es: 'Usa un servidor RAG (p. ej. enowx-rag en localhost:7777) para buscar contexto del proyecto antes de responder. Off = chat normal.',
    fr: 'Utilise un serveur RAG (ex. enowx-rag sur localhost:7777) pour chercher le contexte du projet avant de répondre. Off = chat simple.',
    de: 'Nutzt einen RAG-Server (z. B. enowx-rag auf localhost:7777), um Projektkontext vor der Antwort zu suchen. Aus = normaler Chat.',
    pt: 'Usa um servidor RAG (ex.: enowx-rag em localhost:7777) para buscar contexto do projeto antes de responder. Desligado = chat comum.',
    ar: 'استخدم خادم RAG (مثل enowx-rag على localhost:7777) للبحث في سياق المشروع قبل الرد. معطّل = دردشة عادية.',
  },
  'Jumlah chunk': {
    en: 'Chunk count',
    ja: 'チャンク数',
    ko: '청크 수',
    zh: '分块数量',
    es: 'Número de fragmentos',
    fr: 'Nombre de segments',
    de: 'Anzahl der Chunks',
    pt: 'Número de chunks',
    ar: 'عدد الأجزاء',
  },
  'Ambil daftar model langsung dari provider': {
    en: 'Fetch the model list straight from the provider',
    ja: 'プロバイダーから直接モデル一覧を取得',
    ko: '공급자에게서 모델 목록을 직접 가져오기',
    zh: '直接从提供商获取模型列表',
    es: 'Obtener la lista de modelos directamente del proveedor',
    fr: 'Récupérer la liste des modèles directement auprès du fournisseur',
    de: 'Modellliste direkt vom Anbieter abrufen',
    pt: 'Buscar a lista de modelos direto do provedor',
    ar: 'جلب قائمة النماذج مباشرة من المزوّد',
  },
  'nama model': {
    en: 'model name',
    ja: 'モデル名',
    ko: '모델 이름',
    zh: '模型名称',
    es: 'nombre del modelo',
    fr: 'nom du modèle',
    de: 'Modellname',
    pt: 'nome do modelo',
    ar: 'اسم النموذج',
  },
  'pane melebihi batas ditolak dengan toast': {
    en: 'panes over the limit are rejected with a toast',
    ja: '上限を超えるペインはトーストで拒否されます',
    ko: '한도 초과 페인은 토스트로 거부됩니다',
    zh: '超出限制的窗格会以提示拒绝',
    es: 'los paneles que exceden el límite se rechazan con un aviso',
    fr: 'les panneaux au-delà de la limite sont refusés par un toast',
    de: 'Panes über dem Limit werden mit einem Toast abgelehnt',
    pt: 'painéis além do limite são recusados com um toast',
    ar: 'تُرفض اللوحات الزائدة عن الحد مع تنبيه',
  },
  'dipakai panel AI': {
    en: 'used by the AI panel',
    ja: 'AIパネルで使用',
    ko: 'AI 패널에서 사용',
    zh: '供 AI 面板使用',
    es: 'usado por el panel de IA',
    fr: 'utilisé par le panneau IA',
    de: 'wird vom KI-Panel verwendet',
    pt: 'usado pelo painel de IA',
    ar: 'يُستخدم في لوحة الذكاء الاصطناعي',
  },
  'tiap subagent memanggil provider sendiri — makin banyak, makin cepat habis kuota': {
    en: 'each subagent calls the provider itself — the more there are, the faster the quota drains',
    ja: '各サブエージェントがプロバイダーを呼びます — 多いほどクォータ消費が速くなります',
    ko: '각 서브에이전트가 공급자를 호출합니다 — 많을수록 할당량이 빨리 소진됩니다',
    zh: '每个子代理各自调用提供商 — 越多配额消耗越快',
    es: 'cada subagente llama al proveedor por su cuenta — cuantos más, más rápido se agota la cuota',
    fr: "chaque sous-agent appelle le fournisseur lui-même — plus il y en a, plus le quota s'épuise vite",
    de: 'jeder Subagent ruft den Anbieter selbst auf — je mehr, desto schneller ist das Kontingent weg',
    pt: 'cada subagente chama o provedor por conta própria — quanto mais, mais rápido a cota acaba',
    ar: 'كل وكيل فرعي يستدعي المزوّد بنفسه — كلما زاد عددها نفدت الحصة أسرع',
  },
  'subagent berhenti kalau melewati batas ini — penjaga biaya loop tak berujung': {
    en: 'subagents stop when they pass this limit — a guard against endless-loop costs',
    ja: 'この上限を超えるとサブエージェントは停止 — 無限ループのコスト対策',
    ko: '이 한도를 넘으면 서브에이전트 중지 — 무한 루프 비용 방지',
    zh: '子代理超过此上限即停止 — 防止无限循环的费用',
    es: 'los subagentes se detienen al pasar este límite — protección contra costes de bucles infinitos',
    fr: "les sous-agents s'arrêtent au-delà de cette limite — garde-fou contre les coûts de boucle infinie",
    de: 'Subagenten stoppen beim Überschreiten dieses Limits — Schutz vor Endlosschleifen-Kosten',
    pt: 'subagentes param ao passar deste limite — proteção contra custos de loop infinito',
    ar: 'تتوقف الوكلاء الفرعية عند تجاوز هذا الحد — حماية من تكاليف الحلقات اللانهائية',
  },
  'default TIDAK. Beberapa subagent yang menulis file sama bisa saling menimpa': {
    en: 'default OFF. Several subagents writing the same file can overwrite each other',
    ja: '既定はオフ。同じファイルを書く複数のサブエージェントが上書きし合う恐れがあります',
    ko: '기본 꺼짐. 같은 파일을 쓰는 여러 서브에이전트가 서로 덮어쓸 수 있습니다',
    zh: '默认关闭。多个子代理写同一文件可能互相覆盖',
    es: 'por defecto OFF. Varios subagentes escribiendo el mismo archivo pueden sobrescribirse',
    fr: "désactivé par défaut. Plusieurs sous-agents écrivant le même fichier peuvent s'écraser",
    de: 'standardmäßig AUS. Mehrere Subagenten an derselben Datei können sich überschreiben',
    pt: 'padrão DESLIGADO. Vários subagentes gravando o mesmo arquivo podem se sobrescrever',
    ar: 'الافتراضي مُعطّل. قد تطغى عدة وكلاء فرعية تكتب الملف نفسه على بعضها',
  },
  'kalau dimatikan, hanya ringkasan yang muncul': {
    en: 'when off, only the summary appears',
    ja: 'オフにすると要約のみ表示されます',
    ko: '끄면 요약만 표시됩니다',
    zh: '关闭时仅显示摘要',
    es: 'si se desactiva, solo aparece el resumen',
    fr: 'si désactivé, seul le résumé apparaît',
    de: 'wenn aus, erscheint nur die Zusammenfassung',
    pt: 'se desativado, apenas o resumo aparece',
    ar: 'عند الإيقاف يظهر الملخص فقط',
  },
  'langkah langsung terlipat setelah selesai': {
    en: 'steps collapse right after finishing',
    ja: '完了後すぐにステップが折りたたまれます',
    ko: '완료 직후 단계가 접힙니다',
    zh: '完成后立即折叠步骤',
    es: 'los pasos se pliegan justo al terminar',
    fr: 'les étapes se replient dès la fin',
    de: 'Schritte klappen direkt nach dem Ende ein',
    pt: 'os passos se recolhem logo após terminar',
    ar: 'تُطوى الخطوات فور انتهائها',
  },
  '6 CLI terdeteksi di PATH': {
    en: '6 CLIs detected on PATH',
    ja: 'PATH 上で 6 つの CLI を検出',
    ko: 'PATH에서 CLI 6개 감지',
    zh: '在 PATH 中检测到 6 个 CLI',
    es: '6 CLI detectadas en el PATH',
    fr: '6 CLI détectées dans le PATH',
    de: '6 CLIs im PATH gefunden',
    pt: '6 CLIs detectadas no PATH',
    ar: 'تم اكتشاف 6 أدوات CLI في PATH',
  },
  'Buka folder ekstensi': {
    en: 'Open extensions folder',
    ja: '拡張機能フォルダを開く',
    ko: '확장 폴더 열기',
    zh: '打开扩展文件夹',
    es: 'Abrir la carpeta de extensiones',
    fr: 'Ouvrir le dossier des extensions',
    de: 'Erweiterungsordner öffnen',
    pt: 'Abrir a pasta de extensões',
    ar: 'فتح مجلد الإضافات',
  },
  'Perubahan tema/keymap/bahasa berlaku setelah reload.': {
    en: 'Theme/keymap/language changes apply after a reload.',
    ja: 'テーマ/キーマップ/言語の変更はリロード後に反映されます。',
    ko: '테마/키맵/언어 변경은 새로고침 후 적용됩니다.',
    zh: '主题/键位/语言更改在重新加载后生效。',
    es: 'Los cambios de tema/atajos/idioma se aplican tras recargar.',
    fr: 'Les changements de thème/keymap/langue s\'appliquent après rechargement.',
    de: 'Theme-/Keymap-/Sprachänderungen gelten nach einem Reload.',
    pt: 'Alterações de tema/keymap/idioma aplicam-se após recarregar.',
    ar: 'تُطبَّق تغييرات السمة/الخريطة/اللغة بعد إعادة التحميل.',
  },
  'Zephyr TIDAK membundel binary language server (installer tetap ~7 MB). Server dicari di': {
    en: 'Zephyr does NOT bundle language server binaries (installer stays ~7 MB). Servers are looked up in',
    ja: 'Zephyr は言語サーバーのバイナリを同梱しません（インストーラーは約7MBのまま）。サーバーは次で探されます:',
    ko: 'Zephyr는 언어 서버 바이너리를 포함하지 않습니다 (설치 파일 ~7MB 유지). 서버는 다음에서 찾습니다:',
    zh: 'Zephyr 不捆绑语言服务器二进制文件（安装包保持约 7 MB）。服务器查找位置：',
    es: 'Zephyr NO incluye binarios de servidores de lenguaje (el instalador sigue en ~7 MB). Los servidores se buscan en',
    fr: "Zephyr n'embarque PAS les binaires des serveurs de langage (l'installeur reste ~7 Mo). Les serveurs sont cherchés dans",
    de: 'Zephyr bündelt KEINE Language-Server-Binaries (Installer bleibt ~7 MB). Server werden gesucht in',
    pt: 'Zephyr NÃO inclui binários de servidores de linguagem (o instalador fica em ~7 MB). Os servidores são procurados em',
    ar: 'لا يضم Zephyr ملفات خوادم اللغة (يبقى المثبّت ~7 م.ب). تُبحث الخوادم في',
  },
  'lalu di PATH. Server hanya start saat file bertipe itu dibuka, dan mati sendiri setelah idle.': {
    en: 'then on PATH. A server only starts when a file of that type is opened, and shuts itself down after idle.',
    ja: '次に PATH。サーバーはその種類のファイルを開いたときだけ起動し、アイドル後に自動終了します。',
    ko: '그다음 PATH. 서버는 해당 형식의 파일을 열 때만 시작하고 유휴 후 스스로 종료됩니다.',
    zh: '然后查找 PATH。服务器仅在该类型文件打开时启动，空闲后自动关闭。',
    es: 'y luego en el PATH. El servidor solo arranca al abrir un archivo de ese tipo y se apaga tras inactividad.',
    fr: "puis dans le PATH. Un serveur ne démarre qu'à l'ouverture d'un fichier de ce type et s'arrête après inactivité.",
    de: 'dann im PATH. Ein Server startet nur beim Öffnen einer solchen Datei und beendet sich nach Idle.',
    pt: 'e depois no PATH. O servidor só inicia ao abrir um arquivo desse tipo e se encerra após ociosidade.',
    ar: 'ثم في PATH. يبدأ الخادم فقط عند فتح ملف من ذلك النوع ويتوقف بعد الخمول.',
  },
  'belum ada folder terbuka': {
    en: 'no folder open yet',
    ja: 'フォルダがまだ開かれていません',
    ko: '열린 폴더 없음',
    zh: '尚未打开文件夹',
    es: 'ninguna carpeta abierta aún',
    fr: 'aucun dossier ouvert',
    de: 'noch kein Ordner geöffnet',
    pt: 'nenhuma pasta aberta ainda',
    ar: 'لا مجلد مفتوح بعد',
  },
  'belum ada workspace terbuka': {
    en: 'no workspace open yet',
    ja: 'ワークスペースがまだ開かれていません',
    ko: '열린 워크스페이스 없음',
    zh: '尚未打开工作区',
    es: 'ningún espacio de trabajo abierto aún',
    fr: 'aucun espace de travail ouvert',
    de: 'noch kein Workspace geöffnet',
    pt: 'nenhum workspace aberto ainda',
    ar: 'لا مساحة عمل مفتوحة بعد',
  },
  'Tema aktif:': {
    en: 'Active theme:',
    ja: 'アクティブテーマ:',
    ko: '활성 테마:',
    zh: '当前主题：',
    es: 'Tema activo:',
    fr: 'Thème actif :',
    de: 'Aktives Theme:',
    pt: 'Tema ativo:',
    ar: 'السمة النشطة:',
  },
  '· mode': {
    en: '· mode',
    ja: '· モード',
    ko: '· 모드',
    zh: '· 模式',
    es: '· modo',
    fr: '· mode',
    de: '· Modus',
    pt: '· modo',
    ar: '· الوضع',
  },
  'Merekam chord untuk': {
    en: 'Recording chord for',
    ja: 'コードを記録中:',
    ko: '코드 기록 중:',
    zh: '正在录制组合键：',
    es: 'Grabando combinación para',
    fr: 'Enregistrement du raccourci pour',
    de: 'Kürzel wird aufgezeichnet für',
    pt: 'Gravando atalho para',
    ar: 'تسجيل المزيج لـ',
  },
  'Hapus dari daftar': {
    en: 'Remove from list',
    ja: 'リストから削除',
    ko: '목록에서 제거',
    zh: '从列表移除',
    es: 'Quitar de la lista',
    fr: 'Retirer de la liste',
    de: 'Aus der Liste entfernen',
    pt: 'Remover da lista',
    ar: 'إزالة من القائمة',
  },
  'Ubah port lokal': {
    en: 'Change local port',
    ja: 'ローカルポートを変更',
    ko: '로컬 포트 변경',
    zh: '更改本地端口',
    es: 'Cambiar puerto local',
    fr: 'Changer le port local',
    de: 'Lokalen Port ändern',
    pt: 'Alterar porta local',
    ar: 'تغيير المنفذ المحلي',
  },
  'Nomor port untuk diteruskan': {
    en: 'Port number to forward',
    ja: '転送するポート番号',
    ko: '포워딩할 포트 번호',
    zh: '要转发的端口号',
    es: 'Número de puerto a reenviar',
    fr: 'Numéro de port à rediriger',
    de: 'Weiterzuleitende Portnummer',
    pt: 'Número da porta a encaminhar',
    ar: 'رقم المنفذ المراد تمريره',
  },
  'Private (tanpa riwayat)': {
    en: 'Private (no history)',
    ja: 'プライベート（履歴なし）',
    ko: '비공개 (기록 없음)',
    zh: '私密（无历史）',
    es: 'Privado (sin historial)',
    fr: 'Privé (sans historique)',
    de: 'Privat (ohne Verlauf)',
    pt: 'Privado (sem histórico)',
    ar: 'خاص (بلا سجل)',
  },
  'Pane aktif': {
    en: 'active pane',
    ja: 'アクティブペイン',
    ko: '활성 페인',
    zh: '活动窗格',
    es: 'panel activo',
    fr: 'volet actif',
    de: 'aktives Pane',
    pt: 'painel ativo',
    ar: 'اللوحة النشطة',
  },
  'Pane terminal baru (alt)': {
    en: 'New terminal pane (alt)',
    ja: '新しいターミナルペイン（代替）',
    ko: '새 터미널 페인 (대체)',
    zh: '新建终端窗格（备用）',
    es: 'Nuevo panel de terminal (alt)',
    fr: 'Nouveau volet terminal (alt)',
    de: 'Neues Terminal-Pane (Alt)',
    pt: 'Novo painel de terminal (alt)',
    ar: 'لوحة طرفية جديدة (بديل)',
  },
  'Folder baru': {
    en: 'New folder',
    ja: '新しいフォルダ',
    ko: '새 폴더',
    zh: '新建文件夹',
    es: 'Nueva carpeta',
    fr: 'Nouveau dossier',
    de: 'Neuer Ordner',
    pt: 'Nova pasta',
    ar: 'مجلد جديد',
  },
  'Folder ini repo git': {
    en: 'This folder is a git repo',
    ja: 'このフォルダは git リポジトリです',
    ko: '이 폴더는 git 저장소입니다',
    zh: '此文件夹是 git 仓库',
    es: 'Esta carpeta es un repo git',
    fr: 'Ce dossier est un dépôt git',
    de: 'Dieser Ordner ist ein Git-Repo',
    pt: 'Esta pasta é um repositório git',
    ar: 'هذا المجلد مستودع git',
  },
  'Jadikan root aktif': {
    en: 'Make active root',
    ja: 'アクティブルートにする',
    ko: '활성 루트로 지정',
    zh: '设为活动根目录',
    es: 'Hacer raíz activa',
    fr: 'Définir comme racine active',
    de: 'Als aktive Wurzel festlegen',
    pt: 'Tornar raiz ativa',
    ar: 'تعيين كجذر نشط',
  },
  'Belum disimpan': {
    en: 'Not saved yet',
    ja: '未保存',
    ko: '저장되지 않음',
    zh: '尚未保存',
    es: 'Sin guardar',
    fr: 'Pas encore enregistré',
    de: 'Noch nicht gespeichert',
    pt: 'Ainda não salvo',
    ar: 'لم يُحفظ بعد',
  },
  'Berikutnya (Enter)': {
    en: 'Next (Enter)',
    ja: '次へ（Enter）',
    ko: '다음 (Enter)',
    zh: '下一个（Enter）',
    es: 'Siguiente (Enter)',
    fr: 'Suivant (Entrée)',
    de: 'Weiter (Enter)',
    pt: 'Próximo (Enter)',
    ar: 'التالي (Enter)',
  },
  'Sebelumnya (Shift+Enter)': {
    en: 'Previous (Shift+Enter)',
    ja: '前へ（Shift+Enter）',
    ko: '이전 (Shift+Enter)',
    zh: '上一个（Shift+Enter）',
    es: 'Anterior (Shift+Enter)',
    fr: 'Précédent (Maj+Entrée)',
    de: 'Zurück (Shift+Enter)',
    pt: 'Anterior (Shift+Enter)',
    ar: 'السابق (Shift+Enter)',
  },
  'Buat ulang jawaban ini': {
    en: 'Regenerate this reply',
    ja: 'この返答を再生成',
    ko: '이 답변 다시 생성',
    zh: '重新生成此回复',
    es: 'Regenerar esta respuesta',
    fr: 'Régénérer cette réponse',
    de: 'Diese Antwort neu erzeugen',
    pt: 'Regerar esta resposta',
    ar: 'إعادة توليد هذا الرد',
  },
  'Geser untuk mengubah lebar': {
    en: 'Drag to resize',
    ja: 'ドラッグで幅を変更',
    ko: '끌어서 너비 조절',
    zh: '拖动以调整宽度',
    es: 'Arrastra para cambiar el ancho',
    fr: 'Glisser pour redimensionner',
    de: 'Ziehen, um die Breite zu ändern',
    pt: 'Arraste para redimensionar',
    ar: 'اسحب لتغيير العرض',
  },
  'Filter (teks, source, kode, file)…': {
    en: 'Filter (text, source, code, file)…',
    ja: 'フィルター（テキスト、ソース、コード、ファイル）…',
    ko: '필터 (텍스트, 소스, 코드, 파일)…',
    zh: '筛选（文本、来源、代码、文件）…',
    es: 'Filtrar (texto, origen, código, archivo)…',
    fr: 'Filtrer (texte, source, code, fichier)…',
    de: 'Filtern (Text, Quelle, Code, Datei)…',
    pt: 'Filtrar (texto, origem, código, arquivo)…',
    ar: 'تصفية (نص، مصدر، كود، ملف)…',
  },
  'Tanya atau minta ubah kode… (Enter kirim, Esc tutup)': {
    en: 'Ask or request a code change… (Enter sends, Esc closes)',
    ja: '質問またはコード変更を依頼…（Enterで送信、Escで閉じる）',
    ko: '질문하거나 코드 변경을 요청… (Enter 전송, Esc 닫기)',
    zh: '提问或请求修改代码…（Enter 发送，Esc 关闭）',
    es: 'Pregunta o pide un cambio de código… (Enter envía, Esc cierra)',
    fr: 'Posez une question ou demandez une modification… (Entrée envoie, Échap ferme)',
    de: 'Fragen oder Codeänderung anfordern… (Enter sendet, Esc schließt)',
    pt: 'Pergunte ou peça uma mudança de código… (Enter envia, Esc fecha)',
    ar: 'اسأل أو اطلب تعديل الكود… (Enter للإرسال، Esc للإغلاق)',
  },
  'tanpa language server: jalur diperkirakan dari indentasi': {
    en: 'without a language server: path inferred from indentation',
    ja: '言語サーバーなし: インデントからパスを推定',
    ko: '언어 서버 없음: 들여쓰기로 경로 추정',
    zh: '无语言服务器：根据缩进推测路径',
    es: 'sin servidor de lenguaje: ruta inferida por la sangría',
    fr: "sans serveur de langage : chemin déduit de l'indentation",
    de: 'ohne Language Server: Pfad aus der Einrückung geschätzt',
    pt: 'sem servidor de linguagem: caminho inferido pela indentação',
    ar: 'بدون خادم لغة: يُستنتج المسار من الإزاحة',
  },
  'Path kunci': {
    en: 'Key path',
    ja: 'キーのパス',
    ko: '키 경로',
    zh: '密钥路径',
    es: 'Ruta de la clave',
    fr: 'Chemin de la clé',
    de: 'Schlüsselpfad',
    pt: 'Caminho da chave',
    ar: 'مسار المفتاح',
  },
  'passphrase diketik saat connect': {
    en: 'passphrase typed at connect time',
    ja: 'パスフレーズは接続時に入力します',
    ko: '암호는 연결할 때 입력합니다',
    zh: '连接时输入口令',
    es: 'frase de contraseña se escribe al conectar',
    fr: 'phrase secrète saisie à la connexion',
    de: 'Passphrase wird beim Verbinden eingegeben',
    pt: 'frase-senha digitada ao conectar',
    ar: 'تُكتب عبارة المرور عند الاتصال',
  },
  'Simpan password': {
    en: 'Save password',
    ja: 'パスワードを保存',
    ko: '비밀번호 저장',
    zh: '保存密码',
    es: 'Guardar contraseña',
    fr: 'Enregistrer le mot de passe',
    de: 'Passwort speichern',
    pt: 'Salvar senha',
    ar: 'حفظ كلمة المرور',
  },
  'dipakai sebagai Authorization: Bearer ***': {
    en: 'used as Authorization: Bearer ***',
    ja: 'Authorization: Bearer *** として使用',
    ko: 'Authorization: Bearer *** 로 사용',
    zh: '用作 Authorization: Bearer ***',
    es: 'usado como Authorization: Bearer ***',
    fr: 'utilisé comme Authorization: Bearer ***',
    de: 'wird als Authorization: Bearer *** verwendet',
    pt: 'usado como Authorization: Bearer ***',
    ar: 'يُستخدم كـ Authorization: Bearer ***',
  },
  'entri ditulis ke config; file lama disalin ke .bak': {
    en: 'the entry is written to the config; the old file is copied to .bak',
    ja: 'エントリは config に書き込まれ、旧ファイルは .bak にコピーされます',
    ko: '항목이 config에 기록되고 이전 파일은 .bak으로 복사됩니다',
    zh: '条目写入 config；旧文件复制为 .bak',
    es: 'la entrada se escribe en el config; el archivo antiguo se copia a .bak',
    fr: "l'entrée est écrite dans la config ; l'ancien fichier est copié en .bak",
    de: 'der Eintrag wird in die Config geschrieben; die alte Datei wird als .bak gesichert',
    pt: 'a entrada é gravada no config; o arquivo antigo é copiado para .bak',
    ar: 'يُكتب الإدخال في الإعدادات ويُنسخ الملف القديم إلى .bak',
  },
  'Adapter OpenAI/Anthropic/Gemini untuk panel AI': {
    en: 'OpenAI/Anthropic/Gemini adapters for the AI panel',
    ja: 'AIパネル用の OpenAI/Anthropic/Gemini アダプター',
    ko: 'AI 패널용 OpenAI/Anthropic/Gemini 어댑터',
    zh: '用于 AI 面板的 OpenAI/Anthropic/Gemini 适配器',
    es: 'Adaptadores OpenAI/Anthropic/Gemini para el panel de IA',
    fr: 'Adaptateurs OpenAI/Anthropic/Gemini pour le panneau IA',
    de: 'OpenAI/Anthropic/Gemini-Adapter für das KI-Panel',
    pt: 'Adaptadores OpenAI/Anthropic/Gemini para o painel de IA',
    ar: 'محوّلات OpenAI/Anthropic/Gemini للوحة الذكاء الاصطناعي',
  },
  'Cara pasang latar': {
    en: 'How to set the background',
    ja: '背景の設定方法',
    ko: '배경 설정 방법',
    zh: '如何设置背景',
    es: 'Cómo configurar el fondo',
    fr: "Comment définir l'arrière-plan",
    de: 'So wird der Hintergrund gesetzt',
    pt: 'Como definir o plano de fundo',
    ar: 'كيفية تعيين الخلفية',
  },
  'Hapus semua': {
    en: 'Delete all',
    ja: 'すべて削除',
    ko: '모두 삭제',
    zh: '全部删除',
    es: 'Eliminar todo',
    fr: 'Tout supprimer',
    de: 'Alle löschen',
    pt: 'Excluir tudo',
    ar: 'حذف الكل',
  },
  '0 subagent di panel': {
    en: '0 subagents in the panel',
    ja: 'パネルにサブエージェント 0 個',
    ko: '패널에 서브에이전트 0개',
    zh: '面板中有 0 个子代理',
    es: '0 subagentes en el panel',
    fr: '0 sous-agent dans le panneau',
    de: '0 Subagenten im Panel',
    pt: '0 subagentes no painel',
    ar: 'لا وكلاء فرعيون في اللوحة',
  },
  'Tutup PowerShell': {
    en: 'Close PowerShell',
    ja: 'PowerShellを閉じる',
    ko: 'PowerShell 닫기',
    zh: '关闭 PowerShell',
    es: 'Cerrar PowerShell',
    fr: 'Fermer PowerShell',
    de: 'PowerShell schließen',
    pt: 'Fechar o PowerShell',
    ar: 'إغلاق PowerShell',
  },
  '0 error, 0 warning — buka Problems': {
    en: '0 errors, 0 warnings — open Problems',
    ja: 'エラー0、警告0 — Problemsを開く',
    ko: '오류 0, 경고 0 — Problems 열기',
    zh: '0 个错误，0 个警告 — 打开 Problems',
    es: '0 errores, 0 advertencias — abrir Problems',
    fr: '0 erreur, 0 avertissement — ouvrir Problems',
    de: '0 Fehler, 0 Warnungen — Problems öffnen',
    pt: '0 erros, 0 avisos — abrir Problems',
    ar: '0 أخطاء، 0 تحذيرات — افتح Problems',
  },
  'Lampirkan file aktif: untitled-1 (maks 12KB)': {
    en: 'Attach active file: untitled-1 (max 12KB)',
    ja: 'アクティブファイルを添付: untitled-1（最大12KB）',
    ko: '활성 파일 첨부: untitled-1 (최대 12KB)',
    zh: '附加当前文件：untitled-1（最大 12KB）',
    es: 'Adjuntar archivo activo: untitled-1 (máx 12KB)',
    fr: 'Joindre le fichier actif : untitled-1 (max 12 Ko)',
    de: 'Aktive Datei anhängen: untitled-1 (max. 12KB)',
    pt: 'Anexar arquivo ativo: untitled-1 (máx 12KB)',
    ar: 'إرفاق الملف النشط: untitled-1 (بحد أقصى 12KB)',
  },
  'Lampiran gambar (maks 10 gambar, 3,5 MB masing-masing) — atau Win+Shift+S lalu Ctrl+V': {
    en: 'Image attachments (max 10 images, 3.5 MB each) — or Win+Shift+S then Ctrl+V',
    ja: '画像添付（最大10枚、各3.5MB）— または Win+Shift+S の後 Ctrl+V',
    ko: '이미지 첨부 (최대 10장, 각 3.5MB) — 또는 Win+Shift+S 후 Ctrl+V',
    zh: '图片附件（最多 10 张，每张 3.5 MB）— 或 Win+Shift+S 后 Ctrl+V',
    es: 'Adjuntos de imagen (máx 10 imágenes, 3,5 MB cada una) — o Win+Shift+S y Ctrl+V',
    fr: 'Pièces jointes image (max 10 images, 3,5 Mo chacune) — ou Win+Shift+S puis Ctrl+V',
    de: 'Bildanhänge (max. 10 Bilder, je 3,5 MB) — oder Win+Shift+S, dann Ctrl+V',
    pt: 'Anexos de imagem (máx 10 imagens, 3,5 MB cada) — ou Win+Shift+S e Ctrl+V',
    ar: 'مرفقات الصور (بحد أقصى 10 صور، 3.5 م.ب لكل صورة) — أو Win+Shift+S ثم Ctrl+V',
  },
};
