// terjemahan-model.mjs — terjemahan catatan model (note) di katalog model.
//
// Dipakai scripts/suntik-model.mjs untuk menyuntik ke src/lib/i18n-extra.ts.
// Catatan ini tampil di dropdown pemilih model (panel AI + Settings → Model AI).

export const TERJEMAHAN_MODEL = {
  'terbaru, agentik': {
    en: 'latest, agentic',
    ja: '最新、エージェント向け',
    ko: '최신, 에이전틱',
    zh: '最新，代理型',
    es: 'lo último, agéntico',
    fr: 'dernier, agentique',
    de: 'neuestes, agentisch',
    pt: 'mais recente, agêntico',
    ar: 'الأحدث، وكيلي',
  },
  'terbaru, coding': {
    en: 'latest, coding',
    ja: '最新、コーディング',
    ko: '최신, 코딩',
    zh: '最新，编程',
    es: 'lo último, programación',
    fr: 'dernier, code',
    de: 'neuestes, Coding',
    pt: 'mais recente, código',
    ar: 'الأحدث، للبرمجة',
  },
  'terbaru, coding & agent': {
    en: 'latest, coding & agents',
    ja: '最新、コーディング＆エージェント',
    ko: '최신, 코딩 & 에이전트',
    zh: '最新，编程与代理',
    es: 'lo último, programación y agentes',
    fr: 'dernier, code et agents',
    de: 'neuestes, Coding & Agenten',
    pt: 'mais recente, código e agentes',
    ar: 'الأحدث، للبرمجة والوكلاء',
  },
  'terbaru, default': {
    en: 'latest, default',
    ja: '最新、既定',
    ko: '최신, 기본',
    zh: '最新，默认',
    es: 'lo último, por defecto',
    fr: 'dernier, par défaut',
    de: 'neuestes, Standard',
    pt: 'mais recente, padrão',
    ar: 'الأحدث، افتراضي',
  },
  'terbaru, terbaik': {
    en: 'latest, best',
    ja: '最新、最高',
    ko: '최신, 최고',
    zh: '最新，最佳',
    es: 'lo último, el mejor',
    fr: 'dernier, le meilleur',
    de: 'neuestes, bestes',
    pt: 'mais recente, o melhor',
    ar: 'الأحدث، الأفضل',
  },
  'cepat, hemat': {
    en: 'fast, cheap',
    ja: '高速、低コスト',
    ko: '빠르고 저렴',
    zh: '快速，经济',
    es: 'rápido y económico',
    fr: 'rapide et économique',
    de: 'schnell, günstig',
    pt: 'rápido e econômico',
    ar: 'سريع واقتصادي',
  },
  'cepat, murah': {
    en: 'fast, inexpensive',
    ja: '高速、安価',
    ko: '빠르고 저렴',
    zh: '快速，便宜',
    es: 'rápido y barato',
    fr: 'rapide et bon marché',
    de: 'schnell, preiswert',
    pt: 'rápido e barato',
    ar: 'سريع وغير مكلف',
  },
  cepat: {
    en: 'fast',
    ja: '高速',
    ko: '빠름',
    zh: '快速',
    es: 'rápido',
    fr: 'rapide',
    de: 'schnell',
    pt: 'rápido',
    ar: 'سريع',
  },
  hemat: {
    en: 'cheap',
    ja: '低コスト',
    ko: '저렴',
    zh: '经济',
    es: 'económico',
    fr: 'économique',
    de: 'günstig',
    pt: 'econômico',
    ar: 'اقتصادي',
  },
  'paling hemat': {
    en: 'cheapest',
    ja: '最も低コスト',
    ko: '가장 저렴',
    zh: '最经济',
    es: 'el más económico',
    fr: 'le plus économique',
    de: 'am günstigsten',
    pt: 'o mais econômico',
    ar: 'الأكثر اقتصادية',
  },
  'murah, cepat': {
    en: 'inexpensive, fast',
    ja: '安価、高速',
    ko: '저렴하고 빠름',
    zh: '便宜，快速',
    es: 'barato y rápido',
    fr: 'bon marché, rapide',
    de: 'preiswert, schnell',
    pt: 'barato e rápido',
    ar: 'غير مكلف وسريع',
  },
  'flagship, agentik': {
    en: 'flagship, agentic',
    ja: 'フラッグシップ、エージェント向け',
    ko: '플래그십, 에이전틱',
    zh: '旗舰，代理型',
    es: 'insignia, agéntico',
    fr: 'fleuron, agentique',
    de: 'Flaggschiff, agentisch',
    pt: 'carro-chefe, agêntico',
    ar: 'الرائد، وكيلي',
  },
  'flagship, reasoning': {
    en: 'flagship, reasoning',
    ja: 'フラッグシップ、推論',
    ko: '플래그십, 추론',
    zh: '旗舰，推理',
    es: 'insignia, razonamiento',
    fr: 'fleuron, raisonnement',
    de: 'Flaggschiff, Reasoning',
    pt: 'carro-chefe, raciocínio',
    ar: 'الرائد، استدلالي',
  },
  frontier: {
    en: 'frontier',
    ja: 'フロンティア',
    ko: '프런티어',
    zh: '前沿',
    es: 'frontera',
    fr: 'frontière',
    de: 'Frontier',
    pt: 'fronteira',
    ar: 'الحدودي',
  },
  'generasi 4': {
    en: '4th generation',
    ja: '第4世代',
    ko: '4세대',
    zh: '第四代',
    es: 'cuarta generación',
    fr: '4e génération',
    de: '4. Generation',
    pt: '4ª geração',
    ar: 'الجيل الرابع',
  },
  'generate/edit gambar': {
    en: 'generate/edit images',
    ja: '画像の生成/編集',
    ko: '이미지 생성/편집',
    zh: '生成/编辑图片',
    es: 'generar/editar imágenes',
    fr: 'générer/modifier des images',
    de: 'Bilder erzeugen/bearbeiten',
    pt: 'gerar/editar imagens',
    ar: 'توليد/تحرير الصور',
  },
  'khusus coding': {
    en: 'coding-focused',
    ja: 'コーディング特化',
    ko: '코딩 특화',
    zh: '专为编程',
    es: 'enfocado a programar',
    fr: 'spécialisé code',
    de: 'auf Coding spezialisiert',
    pt: 'focado em código',
    ar: 'مخصص للبرمجة',
  },
  'kualitas tinggi': {
    en: 'high quality',
    ja: '高品質',
    ko: '고품질',
    zh: '高质量',
    es: 'alta calidad',
    fr: 'haute qualité',
    de: 'hohe Qualität',
    pt: 'alta qualidade',
    ar: 'جودة عالية',
  },
  lama: {
    en: 'legacy',
    ja: '旧世代',
    ko: '구형',
    zh: '旧版',
    es: 'antiguo',
    fr: 'ancien',
    de: 'älter',
    pt: 'antigo',
    ar: 'قديم',
  },
  'seimbang (lama)': {
    en: 'balanced (legacy)',
    ja: 'バランス型（旧世代）',
    ko: '균형형 (구형)',
    zh: '均衡（旧版）',
    es: 'equilibrado (antiguo)',
    fr: 'équilibré (ancien)',
    de: 'ausgewogen (älter)',
    pt: 'equilibrado (antigo)',
    ar: 'متوازن (قديم)',
  },
  'umum, versi lama': {
    en: 'general purpose, older version',
    ja: '汎用、旧バージョン',
    ko: '범용, 구버전',
    zh: '通用，旧版本',
    es: 'uso general, versión antigua',
    fr: 'usage général, ancienne version',
    de: 'Allzweck, ältere Version',
    pt: 'uso geral, versão antiga',
    ar: 'عام، إصدار أقدم',
  },
  'penalaran, versi lama': {
    en: 'reasoning, older version',
    ja: '推論、旧バージョン',
    ko: '추론, 구버전',
    zh: '推理，旧版本',
    es: 'razonamiento, versión antigua',
    fr: 'raisonnement, ancienne version',
    de: 'Reasoning, ältere Version',
    pt: 'raciocínio, versão antiga',
    ar: 'استدلالي، إصدار أقدم',
  },
  multimodal: {
    en: 'multimodal',
    ja: 'マルチモーダル',
    ko: '멀티모달',
    zh: '多模态',
    es: 'multimodal',
    fr: 'multimodal',
    de: 'multimodal',
    pt: 'multimodal',
    ar: 'متعدد الوسائط',
  },
  'penalaran dalam': {
    en: 'deep reasoning',
    ja: '深い推論',
    ko: '심층 추론',
    zh: '深度推理',
    es: 'razonamiento profundo',
    fr: 'raisonnement approfondi',
    de: 'tiefes Reasoning',
    pt: 'raciocínio profundo',
    ar: 'استدلال عميق',
  },
  'penalaran panjang': {
    en: 'long reasoning',
    ja: '長い推論',
    ko: '장문 추론',
    zh: '长推理',
    es: 'razonamiento largo',
    fr: 'raisonnement long',
    de: 'langes Reasoning',
    pt: 'raciocínio longo',
    ar: 'استدلال مطوّل',
  },
  reasoning: {
    en: 'reasoning',
    ja: '推論',
    ko: '추론',
    zh: '推理',
    es: 'razonamiento',
    fr: 'raisonnement',
    de: 'Reasoning',
    pt: 'raciocínio',
    ar: 'استدلالي',
  },
  'reasoning dalam': {
    en: 'deep reasoning',
    ja: '深い推論',
    ko: '심층 추론',
    zh: '深度推理',
    es: 'razonamiento profundo',
    fr: 'raisonnement approfondi',
    de: 'tiefes Reasoning',
    pt: 'raciocínio profundo',
    ar: 'استدلال عميق',
  },
  'reasoning, hemat': {
    en: 'reasoning, cheap',
    ja: '推論、低コスト',
    ko: '추론, 저렴',
    zh: '推理，经济',
    es: 'razonamiento, económico',
    fr: 'raisonnement, économique',
    de: 'Reasoning, günstig',
    pt: 'raciocínio, econômico',
    ar: 'استدلالي واقتصادي',
  },
  seimbang: {
    en: 'balanced',
    ja: 'バランス型',
    ko: '균형형',
    zh: '均衡',
    es: 'equilibrado',
    fr: 'équilibré',
    de: 'ausgewogen',
    pt: 'equilibrado',
    ar: 'متوازن',
  },
  profesional: {
    en: 'professional',
    ja: 'プロ向け',
    ko: '프로페셔널',
    zh: '专业',
    es: 'profesional',
    fr: 'professionnel',
    de: 'professionell',
    pt: 'profissional',
    ar: 'احترافي',
  },
  'coding & agent': {
    en: 'coding & agents',
    ja: 'コーディング＆エージェント',
    ko: '코딩 & 에이전트',
    zh: '编程与代理',
    es: 'programación y agentes',
    fr: 'code et agents',
    de: 'Coding & Agenten',
    pt: 'código e agentes',
    ar: 'البرمجة والوكلاء',
  },
  'coding + agent': {
    en: 'coding + agents',
    ja: 'コーディング＋エージェント',
    ko: '코딩 + 에이전트',
    zh: '编程 + 代理',
    es: 'programación + agentes',
    fr: 'code + agents',
    de: 'Coding + Agenten',
    pt: 'código + agentes',
    ar: 'البرمجة + الوكلاء',
  },
  agentik: {
    en: 'agentic',
    ja: 'エージェント向け',
    ko: '에이전틱',
    zh: '代理型',
    es: 'agéntico',
    fr: 'agentique',
    de: 'agentisch',
    pt: 'agêntico',
    ar: 'وكيلي',
  },
  'orkestrasi agent': {
    en: 'agent orchestration',
    ja: 'エージェント編成',
    ko: '에이전트 오케스트레이션',
    zh: '代理编排',
    es: 'orquestación de agentes',
    fr: "orchestration d'agents",
    de: 'Agenten-Orchestrierung',
    pt: 'orquestração de agentes',
    ar: 'تنسيق الوكلاء',
  },
  'bebas, sesuaikan provider': {
    en: 'free-form, match your provider',
    ja: '自由入力、プロバイダーに合わせて',
    ko: '자유 입력, 공급자에 맞게',
    zh: '自由填写，按提供商调整',
    es: 'libre, ajústalo a tu proveedor',
    fr: 'libre, adaptez à votre fournisseur',
    de: 'frei wählbar, passend zum Anbieter',
    pt: 'livre, ajuste ao seu provedor',
    ar: 'حر، حسب مزوّدك',
  },
  'mis. qwen3-coder:32b': {
    en: 'e.g. qwen3-coder:32b',
    ja: '例: qwen3-coder:32b',
    ko: '예: qwen3-coder:32b',
    zh: '例如 qwen3-coder:32b',
    es: 'p. ej. qwen3-coder:32b',
    fr: 'ex. qwen3-coder:32b',
    de: 'z. B. qwen3-coder:32b',
    pt: 'ex.: qwen3-coder:32b',
    ar: 'مثل qwen3-coder:32b',
  },
};
